from typing import Any




machine_group_name_to_id = {
    "LAB-GROUP": 1,
    "SPP-GROUP": 2,
    "SPI-GROUP": 3,
    "PNP-GROUP": 4,
    "OVE-GROUP": 5,
    "AOI-GROUP": 6,
    "AIM-GROUP": 10,
    "PO-GROUP": 11,
    "WSM-GROUP": 12,
    "ICT-GROUP": 13,
    "FPT-GROUP": 14,
    "FTS-GROUP": 15,
    "ASM-GROUP": 16,
    "BCT-GROUP": 17,
    "CC-GROUP": 21,
}

LINE_STATION_ASSOCIATIONS_FIXED: list[tuple[int, int]] = [
    (21, 102),
    (22, 4), (22, 5), (22, 7), (22, 8), (22, 85), (22, 91),
    (23, 27), (23, 63), (23, 75), (23, 76), (23, 86), (23, 92),
    (24, 28), (24, 64), (24, 77), (24, 78), (24, 87), (24, 93),
    (25, 29), (25, 65), (25, 79), (25, 80), (25, 88), (25, 94),
    (26, 30), (26, 66), (26, 81), (26, 82), (26, 89), (26, 95),
    (27, 31), (27, 67), (27, 83), (27, 84), (27, 90), (27, 96),
    (28, 21), (28, 32), (28, 45), (28, 68), (28, 97),
    (29, 22), (29, 33), (29, 46), (29, 69), (29, 98),
    (30, 23), (30, 34), (30, 47), (30, 70), (30, 99),
    (31, 24), (31, 35), (31, 48), (31, 71), (31, 100),
    (32, 25), (32, 36), (32, 49), (32, 72), (32, 101),
    (33, 37), (33, 41), (33, 50), (33, 54), (33, 58),
    (34, 38), (34, 42), (34, 51), (34, 55), (34, 59),
    (35, 39), (35, 43), (35, 52), (35, 56), (35, 60),
    (36, 40), (36, 44), (36, 53), (36, 57), (36, 61),
]



LINES_FIXED: list[dict[str, Any]] = [
    {"id": 21, "name": "ASS-L01"},
    {"id": 22, "name": "FRA-SMT-L01"},
    {"id": 23, "name": "FRA-SMT-L02"},
    {"id": 24, "name": "FRA-SMT-L03"},
    {"id": 25, "name": "FRA-SMT-L04"},
    {"id": 26, "name": "FRA-SMT-L05"},
    {"id": 27, "name": "FRA-SMT-L06"},
    {"id": 28, "name": "THT-L01"},
    {"id": 29, "name": "THT-L02"},
    {"id": 30, "name": "THT-L03"},
    {"id": 31, "name": "THT-L04"},
    {"id": 32, "name": "THT-L05"},
    {"id": 33, "name": "TL-L01"},
    {"id": 34, "name": "TL-L02"},
    {"id": 35, "name": "TL-L03"},
    {"id": 36, "name": "TL-L04"},
]


PCB_COMPONENT_TYPES = [
    ("R",  "Resistor",   "0402"),
    ("C",  "Capacitor",  "0603"),
    ("U",  "IC",         "SOIC-8"),
    ("Q",  "Transistor", "SOT-23"),
    ("D",  "Diode",      "SOD-123"),
    ("L",  "Inductor",   "0805"),
    ("J",  "Connector",  "THT"),
    ("Y",  "Crystal",    "HC-49"),
    ("SW", "Switch",     "THT"),
    ("F",  "Fuse",       "1206"),
]


PCB_PROCESS_STEPS = [
    ("SPI",     "Solder Paste Inspection",      "SMT"),
    ("PNP",     "Pick and Place",               "SMT"),
    ("REFLOW",  "Reflow Oven",                  "SMT"),
    ("AOI_TOP", "AOI Top Side",                 "SMT"),
    ("THT",     "Through Hole Assembly",        "THT"),
    ("WAVE",    "Wave Soldering",               "THT"),
    ("AOI_BOT", "AOI Bottom Side",              "THT"),
    ("ICT",     "In-Circuit Test",              "TEST"),
    ("FUNC",    "Functional Test",              "TEST"),
    ("XRAY",    "X-Ray Inspection",             "TEST"),
    ("PROG",    "Programming",                  "TEST"),
    ("CLEAN",   "Cleaning / Conformal Coating", "FINISH"),
    ("LASER",   "Laser Marking",                "FINISH"),
    ("PACK",    "Packaging & Label",            "FINISH"),
]



ALLOWED_CONDITIONS: list[dict[str, Any]] = [
    {"code": "1000", "desc": "Minor Stoppages & Waiting",  "group_id": 1, "color": "#d6a624"},
    {"code": "1001", "desc": "Cleaning",                   "group_id": 1, "color": "#099f95"},
    {"code": "1002", "desc": "Rate Deviation & Others",    "group_id": 1, "color": "#d12323"},
    {"code": "2000", "desc": "Change Over & Setup",        "group_id": 2, "color": "#4940c9"},
    {"code": "2001", "desc": "Part Shortage",              "group_id": 2, "color": "#d544c8"},
    {"code": "2002", "desc": "Machine Breakdown",          "group_id": 2, "color": "#8b1818"},
    {"code": "3000", "desc": "Preventive Maintenance",     "group_id": 3, "color": "#e6d628"},
    {"code": "3001", "desc": "Inventory Check",            "group_id": 3, "color": "#4daeea"},
    {"code": "3002", "desc": "Fire Drills",                "group_id": 3, "color": "#c56767"},
    {"code": "3003", "desc": "Trial & Pilot Run",          "group_id": 3, "color": "#3a884e"},
    {"code": "3004", "desc": "Meeting",                    "group_id": 3, "color": "#ea7f06"},
    {"code": "3005", "desc": "No Production & Break",      "group_id": 3, "color": "#3e6eac"},
    {"code": "3006", "desc": "Running",                    "group_id": 3, "color": "#13be1e"},
]



MEASUREMENT_CATALOG: list[dict[str, Any]] = [
    {"measure_name": "Paste Volume (%)",          "lower_limit": 75,   "upper_limit": 125,  "nominal": 100,  "tolerance": 25,   "measure_type": "SPI"},
    {"measure_name": "Paste Height (mm)",         "lower_limit": 0.10, "upper_limit": 0.18, "nominal": 0.14, "tolerance": 0.04, "measure_type": "SPI"},
    {"measure_name": "Paste Area (%)",            "lower_limit": 80,   "upper_limit": 120,  "nominal": 100,  "tolerance": 20,   "measure_type": "SPI"},
    {"measure_name": "Peak Temp (C)",             "lower_limit": 235,  "upper_limit": 250,  "nominal": 243,  "tolerance": 7,    "measure_type": "Thermal"},
    {"measure_name": "Time Above 217C (s)",       "lower_limit": 45,   "upper_limit": 90,   "nominal": 60,   "tolerance": 15,   "measure_type": "Thermal"},
    {"measure_name": "Preheat Ramp (C/s)",        "lower_limit": 1.0,  "upper_limit": 3.0,  "nominal": 2.0,  "tolerance": 0.5,  "measure_type": "Thermal"},
    {"measure_name": "Component Offset X (mm)",   "lower_limit": -0.20,"upper_limit": 0.20, "nominal": 0.0,  "tolerance": 0.10, "measure_type": "AOI"},
    {"measure_name": "Component Offset Y (mm)",   "lower_limit": -0.20,"upper_limit": 0.20, "nominal": 0.0,  "tolerance": 0.10, "measure_type": "AOI"},
    {"measure_name": "Rotation Error (deg)",      "lower_limit": -1.5, "upper_limit": 1.5,  "nominal": 0.0,  "tolerance": 0.5,  "measure_type": "AOI"},
    {"measure_name": "Supply Voltage (V)",        "lower_limit": 4.85, "upper_limit": 5.15, "nominal": 5.0,  "tolerance": 0.10, "measure_type": "ICT"},
    {"measure_name": "Resistance R1 (Ohm)",       "lower_limit": 95,   "upper_limit": 105,  "nominal": 100,  "tolerance": 5,    "measure_type": "ICT"},
    {"measure_name": "Capacitance C1 (nF)",       "lower_limit": 90,   "upper_limit": 110,  "nominal": 100,  "tolerance": 10,   "measure_type": "ICT"},
    {"measure_name": "Insulation Resistance (MOhm)","lower_limit": 100,"upper_limit": 1000, "nominal": 500,  "tolerance": 400,  "measure_type": "Functional"},
    {"measure_name": "Current Consumption (mA)",  "lower_limit": 45,   "upper_limit": 55,   "nominal": 50,   "tolerance": 5,    "measure_type": "Functional"},
]

STATIONS_FIXED: list[dict[str, Any]] = [
    {"legacy_id": 4,   "machine_group": "PNP-GROUP", "name": "FRA-PP-L01-01",  "description": "Pick & Place 1"},
    {"legacy_id": 5,   "machine_group": "PNP-GROUP", "name": "FRA-PP-L01-02",  "description": "Pick & Place 2"},
    {"legacy_id": 6,   "machine_group": "PNP-GROUP", "name": "FRA-PP-L01-03",  "description": "Pick & Place 3"},
    {"legacy_id": 7,   "machine_group": "OVE-GROUP", "name": "FRA-OVE-L01-01", "description": "Reflow Oven"},
    {"legacy_id": 8,   "machine_group": "AOI-GROUP", "name": "FRA-AOI-L01-01", "description": "AOI"},
    {"legacy_id": 12,  "machine_group": "OVE-GROUP", "name": "FRA-OVE-L01-02", "description": ""},
    {"legacy_id": 21,  "machine_group": "AIM-GROUP", "name": "THT-AIM-L01-01", "description": None},
    {"legacy_id": 22,  "machine_group": "AIM-GROUP", "name": "THT-AIM-L02-01", "description": None},
    {"legacy_id": 23,  "machine_group": "AIM-GROUP", "name": "THT-AIM-L03-01", "description": None},
    {"legacy_id": 24,  "machine_group": "AIM-GROUP", "name": "THT-AIM-L04-01", "description": None},
    {"legacy_id": 25,  "machine_group": "AIM-GROUP", "name": "THT-AIM-L05-01", "description": None},
    {"legacy_id": 27,  "machine_group": "AOI-GROUP", "name": "FRA-AOI-L02-01", "description": None},
    {"legacy_id": 28,  "machine_group": "AOI-GROUP", "name": "FRA-AOI-L03-01", "description": None},
    {"legacy_id": 29,  "machine_group": "AOI-GROUP", "name": "FRA-AOI-L04-01", "description": None},
    {"legacy_id": 30,  "machine_group": "AOI-GROUP", "name": "FRA-AOI-L05-01", "description": None},
    {"legacy_id": 31,  "machine_group": "AOI-GROUP", "name": "FRA-AOI-L06-01", "description": None},
    {"legacy_id": 32,  "machine_group": "AOI-GROUP", "name": "THT-AOI-L01-01", "description": None},
    {"legacy_id": 33,  "machine_group": "AOI-GROUP", "name": "THT-AOI-L02-01", "description": None},
    {"legacy_id": 34,  "machine_group": "AOI-GROUP", "name": "THT-AOI-L03-01", "description": None},
    {"legacy_id": 35,  "machine_group": "AOI-GROUP", "name": "THT-AOI-L04-01", "description": None},
    {"legacy_id": 36,  "machine_group": "AOI-GROUP", "name": "THT-AOI-L05-01", "description": None},
    {"legacy_id": 37,  "machine_group": "AOI-GROUP", "name": "TL-AOI-L01-01",  "description": None},
    {"legacy_id": 38,  "machine_group": "AOI-GROUP", "name": "TL-AOI-L02-01",  "description": None},
    {"legacy_id": 39,  "machine_group": "AOI-GROUP", "name": "TL-AOI-L03-01",  "description": None},
    {"legacy_id": 40,  "machine_group": "AOI-GROUP", "name": "TL-AOI-L04-01",  "description": None},
    {"legacy_id": 41,  "machine_group": "BCT-GROUP", "name": "TL-BCT-L01-01",  "description": None},
    {"legacy_id": 42,  "machine_group": "BCT-GROUP", "name": "TL-BCT-L02-01",  "description": None},
    {"legacy_id": 43,  "machine_group": "BCT-GROUP", "name": "TL-BCT-L03-01",  "description": None},
    {"legacy_id": 44,  "machine_group": "BCT-GROUP", "name": "TL-BCT-L04-01",  "description": None},
    {"legacy_id": 45,  "machine_group": "CC-GROUP",  "name": "THT-CC-L01-01",  "description": None},
    {"legacy_id": 46,  "machine_group": "CC-GROUP",  "name": "THT-CC-L02-01",  "description": None},
    {"legacy_id": 47,  "machine_group": "CC-GROUP",  "name": "THT-CC-L03-01",  "description": None},
    {"legacy_id": 48,  "machine_group": "CC-GROUP",  "name": "THT-CC-L04-01",  "description": None},
    {"legacy_id": 49,  "machine_group": "CC-GROUP",  "name": "THT-CC-L05-01",  "description": None},
    {"legacy_id": 50,  "machine_group": "FPT-GROUP", "name": "TL-FPT-L01-01",  "description": None},
    {"legacy_id": 51,  "machine_group": "FPT-GROUP", "name": "TL-FPT-L02-01",  "description": None},
    {"legacy_id": 52,  "machine_group": "FPT-GROUP", "name": "TL-FPT-L03-01",  "description": None},
    {"legacy_id": 53,  "machine_group": "FPT-GROUP", "name": "TL-FPT-L04-01",  "description": None},
    {"legacy_id": 54,  "machine_group": "FTS-GROUP", "name": "TL-FTS-L01-01",  "description": None},
    {"legacy_id": 55,  "machine_group": "FTS-GROUP", "name": "TL-FTS-L02-01",  "description": None},
    {"legacy_id": 56,  "machine_group": "FTS-GROUP", "name": "TL-FTS-L03-01",  "description": None},
    {"legacy_id": 57,  "machine_group": "FTS-GROUP", "name": "TL-FTS-L04-01",  "description": None},
    {"legacy_id": 58,  "machine_group": "ICT-GROUP", "name": "TL-ICT-L01-01",  "description": None},
    {"legacy_id": 59,  "machine_group": "ICT-GROUP", "name": "TL-ICT-L02-01",  "description": None},
    {"legacy_id": 60,  "machine_group": "ICT-GROUP", "name": "TL-ICT-L03-01",  "description": None},
    {"legacy_id": 61,  "machine_group": "ICT-GROUP", "name": "TL-ICT-L04-01",  "description": None},
    {"legacy_id": 63,  "machine_group": "OVE-GROUP", "name": "FRA-OVE-L02-01", "description": None},
    {"legacy_id": 64,  "machine_group": "OVE-GROUP", "name": "FRA-OVE-L03-01", "description": None},
    {"legacy_id": 65,  "machine_group": "OVE-GROUP", "name": "FRA-OVE-L04-01", "description": None},
    {"legacy_id": 66,  "machine_group": "OVE-GROUP", "name": "FRA-OVE-L05-01", "description": None},
    {"legacy_id": 67,  "machine_group": "OVE-GROUP", "name": "FRA-OVE-L06-01", "description": None},
    {"legacy_id": 68,  "machine_group": "PO-GROUP",  "name": "THT-PO-L01-01",  "description": None},
    {"legacy_id": 69,  "machine_group": "PO-GROUP",  "name": "THT-PO-L02-01",  "description": None},
    {"legacy_id": 70,  "machine_group": "PO-GROUP",  "name": "THT-PO-L03-01",  "description": None},
    {"legacy_id": 71,  "machine_group": "PO-GROUP",  "name": "THT-PO-L04-01",  "description": None},
    {"legacy_id": 72,  "machine_group": "PO-GROUP",  "name": "THT-PO-L05-01",  "description": None},
    {"legacy_id": 75,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L02-01",  "description": None},
    {"legacy_id": 76,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L02-02",  "description": None},
    {"legacy_id": 77,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L03-01",  "description": None},
    {"legacy_id": 78,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L03-02",  "description": None},
    {"legacy_id": 79,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L04-01",  "description": None},
    {"legacy_id": 80,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L04-02",  "description": None},
    {"legacy_id": 81,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L05-01",  "description": None},
    {"legacy_id": 82,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L05-02",  "description": None},
    {"legacy_id": 83,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L06-01",  "description": None},
    {"legacy_id": 84,  "machine_group": "PNP-GROUP", "name": "FRA-PP-L06-02",  "description": None},
    {"legacy_id": 85,  "machine_group": "SPI-GROUP", "name": "FRA-SPI-L01-01", "description": None},
    {"legacy_id": 86,  "machine_group": "SPI-GROUP", "name": "FRA-SPI-L02-01", "description": None},
    {"legacy_id": 87,  "machine_group": "SPI-GROUP", "name": "FRA-SPI-L03-01", "description": None},
    {"legacy_id": 88,  "machine_group": "SPI-GROUP", "name": "FRA-SPI-L04-01", "description": None},
    {"legacy_id": 89,  "machine_group": "SPI-GROUP", "name": "FRA-SPI-L05-01", "description": None},
    {"legacy_id": 90,  "machine_group": "SPI-GROUP", "name": "FRA-SPI-L06-01", "description": None},
    {"legacy_id": 91,  "machine_group": "SPP-GROUP", "name": "FRA-SPP-L01-01", "description": None},
    {"legacy_id": 92,  "machine_group": "SPP-GROUP", "name": "FRA-SPP-L02-01", "description": None},
    {"legacy_id": 93,  "machine_group": "SPP-GROUP", "name": "FRA-SPP-L03-01", "description": None},
    {"legacy_id": 94,  "machine_group": "SPP-GROUP", "name": "FRA-SPP-L04-01", "description": None},
    {"legacy_id": 95,  "machine_group": "SPP-GROUP", "name": "FRA-SPP-L05-01", "description": None},
    {"legacy_id": 96,  "machine_group": "SPP-GROUP", "name": "FRA-SPP-L06-01", "description": None},
    {"legacy_id": 97,  "machine_group": "WSM-GROUP", "name": "THT-WSM-L01-01", "description": None},
    {"legacy_id": 98,  "machine_group": "WSM-GROUP", "name": "THT-WSM-L02-01", "description": None},
    {"legacy_id": 99,  "machine_group": "WSM-GROUP", "name": "THT-WSM-L03-01", "description": None},
    {"legacy_id": 100, "machine_group": "WSM-GROUP", "name": "THT-WSM-L04-01", "description": None},
    {"legacy_id": 101, "machine_group": "WSM-GROUP", "name": "THT-WSM-L05-01", "description": None},
    {"legacy_id": 102, "machine_group": "ASM-GROUP", "name": "ASS-ASM-L01-01", "description": None},
]


