services:
  my_postgres_v3:
    image: timescale/timescaledb:latest-pg16
    container_name: my_postgres_v3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  core:
    build:
      context: ./
      dockerfile: Dockerfile
    image: core:latest
    container_name: core-1
    ports:
      - "8011:8011"
    volumes:
      - "./:/app"
    environment:
      DATABASE_URL: postgresql://postgres:admin123@host.docker.internal:5435/postgres
    #  DB_HOST: my_postgres_v3
    #  DB_PORT: 5432
    #  DB_NAME: postgres
    #  DB_USER: postgres
    #  DB_PASSWORD: admin123
    depends_on:
      - my_postgres_v3
    restart: always

  my_grafana_3:
    image: grafana/grafana:latest
    container_name: my_grafana_3
    ports:
      - "3000:3000"
    environment:
        GF_SMTP_ENABLED: "true"
        GF_SMTP_HOST: "smtp.gmail.com:587"
        GF_SMTP_USER: "eya.kos2015@gmail.com"
        GF_SMTP_PASSWORD: "bmsp kewn szxr hdmi"
        GF_SMTP_FROM_ADDRESS: "eya.kos2015@gmail.com"
        GF_SMTP_FROM_NAME: "Grafana Alerts"
        GF_SMTP_STARTTLS_POLICY: "OpportunisticStartTLS"
    volumes:
      - grafana_data:/var/lib/grafana
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - my_postgres_v3
volumes:
  postgres_data:
  grafana_data: